### ISSUE TITLE
Can not connect internet when connect to wifi

### ISSUE THREAD

**Issue by dainguyenSH** [SamsungARTIK/artik-sdk-js#5]
Hi,

I have a problem when connect wifi for artik. After Artik connects to wifi, it does  not connect to Internet ultil I run command "dhclient wlan0". One more problem, when I call connect() method then its SSID will disappear for a while about 2 or 3 seconds and my phone will be disconnected to Artik.  Help me, please!

**Comment by glemercier** [comment]
What are you using for connecting to Wifi? There are several alternatives:

- wpa_supplicant: it does not handle DHCP therefore it's expected that you call `dhclient`
- Own program using ARTIK SDK: The wifi module only allows connection to the WiFi hotspot, once connected you need to use the DHCP client API of the network module to get an IP address
- connman: this network manager service will handle everything, if you configure it properly it will automatically issue a DHCP request to get an IP address after successful connection, and you won't need to call `dhclient`.
